Develop
mate-academy/js_2048_game pull request #1007
Opened 2024-10-24 15:34 UTC by NataliaDavida

- [DEMO LINK](https://NataliaDavida.github.io/js_2048_game/)

2024-10-24 15:37 UTC, etojeDenys requested changes
fix your demo link or feel free to ask for some help in the chat how to to that

2024-10-24 15:37 UTC, etojeDenys commented on src/scripts/main.js
> +    }
rewrite it using the switch case

2024-10-24 15:37 UTC, etojeDenys commented on src/scripts/main.js
> +  }
```
game.getScore();
game.updateDOM();
game.getStatus();
```
you can just move it after the switch case and remove all these functions

2024-10-27 08:56 UTC, TarasHoliuk commented
1. The new tile shouldn't appear if after clicking the arrow button nothing was changed:

![image](https://github.com/user-attachments/assets/3b1a1479-9067-4c35-a462-3e4e8666ae0b)

Then click 'Left', result - "2" appeared:
![image](https://github.com/user-attachments/assets/b493dd3c-7f3f-48e6-b044-51b6400d9a06)

So you have to check if something changed before adding a new tile

2. The "restart" button doesn't work after loosing game:

![image](https://github.com/user-attachments/assets/de33e4e9-4f1f-477f-8371-8e3daf62e9f7)

2024-10-27 08:56 UTC, TarasHoliuk requested changes

2024-10-27 08:56 UTC, TarasHoliuk commented on src/modules/Game.class.js
> +    if (this.moved) {
Seems it doesn't work properly

2024-10-27 08:56 UTC, TarasHoliuk commented on src/modules/Game.class.js
> +      }
This part (almost all method actually) is exactly the same as in moveLeft method

Please, try to reuse some logic between "move" functions

2024-10-27 08:56 UTC, TarasHoliuk commented on src/modules/Game.class.js
> +    } else if (this.status === 'playing') {
What if status is 'lose'?

2026-03-25 17:39 UTC, Anton-Kuchmasov requested changes
DEMO link looks broken :(

<img width="494" height="402" alt="Image" src="https://github.com/user-attachments/assets/3e262040-1ba4-4497-8b31-3afdcd0a7de6" />

Would you mind to add

"homepage": "js_2048_game"

to your `package.json` file, save it, add-commit-push and then re-deploy your solution again?

2026-03-26 07:29 UTC, closed without merging