add solution
mate-academy/js_2048_game pull request #1059
Opened 2024-12-03 18:10 UTC by futdevelop

2024-12-04 09:51 UTC, etojeDenys requested changes
don't forget to provide the demo link

2024-12-05 18:45 UTC, etojeDenys requested changes
add the demo link from readme.md file into the pr description

2024-12-06 08:33 UTC, volodymyr-soltys97 requested changes
Good job!
To improve:
1. Add a favicon on the page 
<img width="151" alt="image" src="https://github.com/user-attachments/assets/b4eca9a0-1d97-4b67-acf7-363c4e8fd1c6">

2. You need to reset dashboard when we don't start the game 
<img width="492" alt="image" src="https://github.com/user-attachments/assets/9870ce79-9d77-453d-bf43-0f82f5387ead">

3. You need to reset the game after press the reset immediately 
<img width="560" alt="image" src="https://github.com/user-attachments/assets/1d26c2cf-c838-485c-9666-f4590e8c8d74">

2024-12-09 06:48 UTC, volodymyr-soltys97 requested changes
Hi, the demo link isn't working, you need to make a deploy and check it after on the demo 
<img width="792" alt="image" src="https://github.com/user-attachments/assets/7e1837ff-24a7-43d0-88d4-dc176fb4362e">

2024-12-09 19:22 UTC, etojeDenys approved these changes

2024-12-09 19:22 UTC, etojeDenys commented on src/modules/Game.class.js
> +    console.log('start');
you don't need that

2024-12-09 19:22 UTC, etojeDenys commented on src/scripts/main.js
> +  //   console.log(board)
and remove all comments

2025-05-02 14:00 UTC, closed without merging