add silution
mate-academy/js_2048_game pull request #1067
Opened 2024-12-09 10:58 UTC by gorbachovam00

- [DEMO LINK](https://gorbachovam00.github.io/js_2048_game/)

2024-12-09 12:13 UTC, VitaliyBondarenko1982 requested changes
Good job.
Please check comments.

2024-12-09 12:13 UTC, VitaliyBondarenko1982 commented on src/scripts/main.js
> +  // });
do not keep commented code

2024-12-09 12:13 UTC, VitaliyBondarenko1982 commented on src/scripts/main.js
> +    if (game.getStatus() !== 'IN_PROGRESS') {
move to constants statuses.
better to palce all statuces strings in object.

2024-12-09 12:13 UTC, VitaliyBondarenko1982 commented on src/scripts/main.js
> +class Game {
why you wrote class Game in main.js?
move code to /modules/Game.class and import here (uncomment code above)

2024-12-11 18:14 UTC, etojeDenys requested changes
I can play the game even if I don't click on the Start button
<img width="643" alt="image" src="https://github.com/user-attachments/assets/0799ee0e-860f-499f-8120-1a4b5a9495f7" />

2. do not create the new cell if the board didn't change after move

https://github.com/user-attachments/assets/03e5c337-063b-4eca-b3d8-499ca8ec9021

2024-12-16 15:53 UTC, volodymyr-soltys97 requested changes
Hi, you need to fix demo link and check it after 
<img width="510" alt="image" src="https://github.com/user-attachments/assets/a1a89351-5ad3-4a02-bf2d-337736ed22b6" />

Add a favicon on the page 
<img width="125" alt="image" src="https://github.com/user-attachments/assets/e4ce0674-1fd1-4558-b2c1-b91a00a779d3" />

2025-01-09 10:23 UTC, closed without merging