solution
mate-academy/js_2048_game pull request #298
Opened 2023-05-12 11:18 UTC by Nikoramo

- [DEMO LINK](https://Nikoramo.github.io/js_2048_game/)

2023-05-12 12:15 UTC, sTorba24 approved these changes
Good work!

2023-05-12 12:15 UTC, sTorba24 commented on src/scripts/main.js
> +          }
so return just condition. If it's true you return true
```suggestion
          return item.children[i].textContent && !item.children[i - 1].textContent;
```

2023-05-12 12:15 UTC, sTorba24 commented on src/scripts/main.js
> +      if (a.textContent === '') {
```suggestion
      if (!a.textContent) {
```

2023-05-12 12:15 UTC, sTorba24 commented on src/scripts/main.js
> +      if (a.textContent === '') {
fix everywhere

2023-06-15 06:46 UTC, DarkMistyRoom requested changes
I've found one moment about horizontal merging. Look at the bottom line when I click left only 2s should merge not all of the cells [VIDEO](https://www.loom.com/share/11f09a6ab95e4c3dbd8ccf3f58b7dc57?sid=cbbd1aac-cbe6-4d48-8a9b-fad22a3f9afb)

2023-06-15 17:06 UTC, closed without merging