Develop
mate-academy/js_2048_game pull request #33
Opened 2021-05-09 22:35 UTC by Dinexpod

[DEMO LINK](https://Dinexpod.github.io/js_2048_game/)

2021-05-10 07:25 UTC, Dinexpod commented
Мощна задачка) Сподобалось) Тільки от в оригіналі воно якось так рухається по всим кліточкам а в мене пропадає в одній і зразу появляється там деповинна стати, хоч я і робив щоб кожну проходило, всеодно

2021-05-10 20:03 UTC, vkryvytskyi requested changes
https://user-images.githubusercontent.com/38065883/117717338-5c599780-b1e3-11eb-9313-dbdbf32931bb.mov

Я могу через html отредактировать поле и сделать сам себе ячейки по 2048
Также после рестарта остался счет предыдущей игры

Тебе нужно все данные игры хранить в JS, и не опираться на HTML
Создай двумерный массив(матрицу), и четыре функции(это основные, могут быть дополнительные еще):
- первая будет проверять есть ли в массиве пустые ячейки чтобы сгенирировать новое значение, и проверять возможность хода(это либо наличие пустых ячеек, либо два одинаковых числа рядом)
- вторая будет генерировать в массив новые значения(двойку или четверку)
- треться будет после каждого шага искать есть ли одинаковые значения, склеивать их и в зависимости от этого тоже обновлять массив
- ну и четвертая после каждого нажатия кнопки и предыдущих трех функций будет отрисовывать изменения в HTML

2021-05-13 22:56 UTC, Dinexpod commented
То что можно было самому менять ячейки и не апдейтился счет поправил

2021-05-17 15:09 UTC, vkryvytskyy approved these changes

2026-05-10 22:11 UTC, closed without merging