Develop
mate-academy/js_2048_game pull request #436
Opened 2023-08-04 18:10 UTC by RuslanMelnykFE

2023-08-04 18:18 UTC, nazarmatsevych requested changes
Code looks interesting but demo link doesn't work, try to fix it and put this link to your pull request description

2023-08-05 10:36 UTC, TarasHoliuk requested changes
your demo link still doesn't work - feel free to ask in the chat if you need help
![image](https://github.com/mate-academy/js_2048_game/assets/86923089/55197eab-c69a-4f49-93d9-9d816115f7d8)

2023-08-05 10:36 UTC, TarasHoliuk commented on src/scripts/main.js
> +//==============================================================
use regions on development stage, but delete it before pushing changes

2023-08-05 10:36 UTC, TarasHoliuk commented on src/scripts/main.js
> +view.init();
it seems like you call an empty method

2023-08-06 16:12 UTC, closed without merging