2048 game
mate-academy/js_2048_game pull request #614
Opened 2023-12-09 15:27 UTC by BodyaKutsyk

2023-12-10 14:50 UTC, anastasiiavorobiova requested changes
Great work! 
<img width="669" alt="Screenshot 2023-12-10 at 16 37 38" src="https://github.com/mate-academy/js_2048_game/assets/135232001/f6da8586-8830-4e87-8fc9-74ade093a897">
The restart button doesn't clear the previous game field

2023-12-11 09:58 UTC, DarkMistyRoom requested changes
Great job! 
Hide "Game over" message after starting a new game
<img width="564" alt="image" src="https://github.com/mate-academy/js_2048_game/assets/98764641/2bad72c3-1d45-4eca-8169-ca235427df57">

2023-12-11 10:33 UTC, VitaliyBondarenko1982 requested changes
Almost done.
Check such bug.
After click on start button fills each cell on the board. 
![2048](https://github.com/mate-academy/js_2048_game/assets/33029864/c1a2fe10-d41f-483a-83c4-ff794ab10e42)

2023-12-11 10:47 UTC, VitaliyBondarenko1982 approved these changes
Well done.

2026-07-11 19:06 UTC, closed without merging