1
mate-academy/js_2048_game pull request #63
Opened 2022-02-20 18:44 UTC by serhii-dvorets

https://serhii-dvorets.github.io/js_2048_game/

2022-02-22 09:38 UTC, vitaliy-martynyuk requested changes
new cells are generated even if none of the existing cells moved after any control button was pressed. also your `leftAction` differs slightly from `rightAction`(`for` loop conditions and the part of code after `win` condition). the same thing with the `upAction` and `downAction`. you can try creating `horizontalMove` and `verticalMove` functions with required properties to keep your code DRY
<img width="449" alt="Screen Shot 2022-02-22 at 11 07 51 AM" src="https://user-images.githubusercontent.com/84335906/155099618-9da81565-524f-40b8-bbb2-f4c339b58693.png">

<img width="415" alt="Screen Shot 2022-02-22 at 11 07 59 AM" src="https://user-images.githubusercontent.com/84335906/155099602-fdf3bf83-b8aa-4b29-8aff-8294efc8448e.png">

2022-02-22 09:38 UTC, vitaliy-martynyuk commented on src/scripts/main.js
> +      cell.textContent = getRandomNumber();
```suggestion
    if (index === number1 || index === number2) {
      cell.textContent = getRandomNumber();
    }
```

2022-02-22 09:38 UTC, vitaliy-martynyuk commented on src/scripts/main.js
> +  });
```suggestion
  const existingNumbers = [...cels].filter(item => item.textContent);
  let cellIndex;
```

2022-02-23 14:01 UTC, vitaliy-martynyuk requested changes
two cells at the beginning of the game have no background
<img width="433" alt="Screen Shot 2022-02-23 at 3 57 46 PM" src="https://user-images.githubusercontent.com/84335906/155334190-903b0903-1583-418c-a8a1-487ddaf38cf7.png">
`loseMessage()` logic doesn't work properly
<img width="448" alt="Screen Shot 2022-02-23 at 3 58 17 PM" src="https://user-images.githubusercontent.com/84335906/155334260-319c597b-72a4-43a9-9d59-fdc773a88a50.png">

2022-02-23 15:03 UTC, vitaliy-martynyuk requested changes, later dismissed
the cells are still active after the `You lose! Restart the game?` message appears

2022-02-28 11:38 UTC, varseniuk requested changes
Твою гру зраз легко зламати за допомогою devTools. Зверни увагу, що в іграх ніхто не опирається на дані в DOM дереві, це небезпечно і ненадійно. Користувач не має мати можливості якось повпливати на результат через html. Тому, в даному випадку для гри було б добре використовувати масив як поле і працювати з ним.

https://user-images.githubusercontent.com/66570142/155974936-93d7c5df-3c63-4b9b-be24-b08b719706d2.mov

2022-03-04 12:39 UTC, varseniuk approved these changes

2025-08-26 11:05 UTC, closed without merging