add task solution
mate-academy/js_2048_game pull request #664
Opened 2024-01-15 07:18 UTC by SerjDSA

[DEMO LINK](https://serjdsa.github.io/js_2048_game/)

2024-01-15 07:31 UTC, etojeDenys requested changes
1. why do you show zero on empty cells, let's just make the empty cell like in reference
<img width="468" alt="image" src="https://github.com/mate-academy/js_2048_game/assets/70220667/aea1f0a2-310d-4ccf-bb55-60f92f1c28d0">


2. when we don't have any cells to merge then do not add another one

https://github.com/mate-academy/js_2048_game/assets/70220667/5fe924b8-9abe-45e6-9033-f2e4ccd1a944

2024-01-15 07:41 UTC, lerastarynets requested changes
You still have zeros in cells and new number appear on every arrow button click, even if cells can't be moved/merged

2024-01-15 09:15 UTC, SerjDSA reviewed
[DEMO LINK](https://serjdsa.github.io/js_2048_game/)

2024-01-15 09:35 UTC, DarkMistyRoom requested changes
- fix please these issues [video1](https://www.loom.com/share/cec3857c087547e4951d1aac89fb01df?sid=df1f92e0-e2fd-4193-9c87-33e532d3785f)

[video2](https://www.loom.com/share/9b11906869154effb0266c7a9d8f47f7?sid=dd50e8b1-06f1-4fcc-ba8c-65bc0a99dfd1)

- why do I lose? There are tiles that could be merged
<img width="418" alt="image" src="https://github.com/mate-academy/js_2048_game/assets/98764641/c5f1a1fa-2c04-47d5-af6d-999d3ac54cd0">

2024-01-15 09:35 UTC, DarkMistyRoom commented on src/index.html
> +            id="cell-1-3"></td>
fix the code style

2024-01-15 12:47 UTC, lerastarynets requested changes
I keep loosing, while there are still cells that can be merged
<img width="463" alt="Screenshot at Jan 15 14-45-23" src="https://github.com/mate-academy/js_2048_game/assets/77551820/cb428e77-a186-40f8-af4c-eda8a4e07185">

2024-01-16 06:42 UTC, SerjDSA reviewed
[DEMO LINK](https://serjdsa.github.io/js_2048_game/)

2024-01-16 07:32 UTC, etojeDenys requested changes
still can reproduce it
https://github.com/mate-academy/js_2048_game/assets/70220667/5f8c57da-1515-4b68-acae-312350b3b767

2024-01-16 07:48 UTC, etojeDenys requested changes
https://github.com/mate-academy/js_2048_game/assets/70220667/24db0dae-f78e-4570-b088-54f9707fc9c5

feel free to ask for some help in the chat, if you don't know how to fix that

2024-01-16 08:21 UTC, SerjDSA reviewed
[DEMO LINK](https://serjdsa.github.io/js_2048_game/)

2024-01-16 10:01 UTC, lerastarynets requested changes
Pls watch the video review [via the link](https://www.awesomescreenshot.com/video/24074540?key=7dc0afa129d4923bf2535c9846f9e755) :)

2024-01-16 10:03 UTC, SerjDSA reviewed
[DEMO LINK](https://serjdsa.github.io/js_2048_game/)

2024-01-17 12:22 UTC, closed without merging