asd
mate-academy/js_2048_game pull request #812
Opened 2024-06-22 18:45 UTC by jdifek

- [DEMO LINK](https://jdifek.github.io/js_2048_game/)

2024-06-22 19:55 UTC, GUSILLUS requested changes
GJ!

Try to implement game over message, because i don't have available moves but I still can't play
![Uploading image.png…]()

2024-06-23 07:29 UTC, TarasHoliuk commented
1. When I lose the game and press `Restart`, then start clicking arrow buttons I see this (button still says Start and I see the message below), but I can play:

![image](https://github.com/mate-academy/js_2048_game/assets/86923089/2746f002-e4e2-4293-b495-b42b94f57423)

2. You shouldn't add a new tile when after the arrow button click nothing changed:
- Current field:
![image](https://github.com/mate-academy/js_2048_game/assets/86923089/11fe4c4a-765f-4dc9-a746-ebc60bd218fd)

- I pressed left (nothing changed, but the new tile was added):
![image](https://github.com/mate-academy/js_2048_game/assets/86923089/da4cd63c-7465-4ad1-a6e9-df2a84d0531f)

2024-06-23 07:34 UTC, TarasHoliuk requested changes
For some reason, tests can't start
Try to fix it (ask for the help in the chat if you need)

2024-06-23 07:34 UTC, TarasHoliuk commented on src/modules/Game.class.js
> +    if (this.status === Game.STATUS_WIN || this.status === Game.STATUS_LOSE) {
Maybe you shouldn't do anything when the status is IDLE as well. See the error in the comments

2024-06-23 07:34 UTC, TarasHoliuk commented on src/scripts/main.js
> +  if (e.key === 'ArrowDown') {
You can use switch here

2024-06-23 11:02 UTC, closed without merging