Build the page
mate-academy/js_2048_game pull request #938
Opened 2024-09-15 16:53 UTC by mishakoshilka

- [DEMO LINK](https://mishakoshilka.github.io/js_2048_game/)

2024-09-15 18:56 UTC, etojeDenys requested changes

2024-09-15 18:56 UTC, etojeDenys commented on src/scripts/main.js
> +    }
rewrite it using the switch case

2024-09-15 18:56 UTC, etojeDenys commented on src/scripts/main.js
> +    }
you can move this logic after all cases

2024-09-16 02:25 UTC, SanyaBratashchuk approved these changes

2024-12-27 08:52 UTC, closed without merging