my solution
mate-academy/js_2048_game pull request #968
Opened 2024-10-03 18:10 UTC by viktalfrontend

2024-10-03 18:18 UTC, TarasHoliuk requested changes
Have you tried to fix tests? If no at least try it. Ask for help in the chat if you need 🙂

2024-10-03 18:18 UTC, TarasHoliuk commented on src/modules/Game.class.js
>      console.log(initialState);
remove it

2024-10-03 18:18 UTC, TarasHoliuk commented on src/scripts/main.js
> +  if (game.status === GameStatus.WIN || game.status === GameStatus.LOSE) {
I can start playing even if didn't click start button yet:

![image](https://github.com/user-attachments/assets/5c1081f7-e595-4f55-9adf-e483ae784f4a)

2024-10-03 18:18 UTC, TarasHoliuk commented on src/modules/Game.class.js
> +    this.addRandomNumber();
you shouldn't add a new number if the field didn't change after button click

2024-10-04 14:54 UTC, viktalfrontend commented
until no one helped to correct the tests, I am sending the work as it is

2024-10-04 14:59 UTC, anastasiiavorobiova requested changes
There are a lot of tests failing. Try to pass them. Feel free to ask for help in the chat

2024-10-06 13:32 UTC, closed without merging

2024-10-06 14:46 UTC, VitaliyBondarenko1982 approved these changes
Good job.
Works correctly.